### ISSUE TITLE
Openning content in desktop application failed, epub, h5p, xapi

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#840] opened 2024-02-13 12:49 UTC
**Describe the bug**
Not able to open   epub, h5p, and xapi contents

**To Reproduce**
using tester1/159753
1. Go to Courses, Final Course before release
2. Browse the content

**Expected behavior**

**Screenshots**
[[If applicable, add screenshots to help explain your problem.](https://www.veed.io/view/60e2db04-08ef-4dd2-99c5-171cc1e1797a?panel=share)](https://www.veed.io/view/60e2db04-08ef-4dd2-99c5-171cc1e1797a?panel=share)

**Desktop (please complete the following information):**
 - OS: Win 11 pro

- Version 0.4.66

**Comment by mhdosman** [comment] 2024-02-13 12:55
The same for Mobile

https://github.com/UstadMobile/UstadMobile/assets/153509442/38028a2a-c5e2-46c9-a037-0c0edf1546f5


![WhatsApp Image 2024-02-13 at 15 54 23_aabcd4c3](https://github.com/UstadMobile/UstadMobile/assets/153509442/8ab48808-d6e8-4cf2-83e4-f13a43f6fc8f)

**Comment by mikedawson** [comment] 2024-02-16 14:11
@mhdosman this has been fixed in version 0.4.73 (which is now live on staging server).

[Screencast from 2024-02-16 18-00-03.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/ff9d7c8f-c2ff-4744-9da6-5898cc3384e0)

This was caused by a conflict with the Apache server compression. This has been resolved by updating the http storage / caching system within Ustad to use gzip and set the content-encoding field itself, and to ensure that all http requests run by the app (Desktop and Android) handle accept-encoding / content-encoding themselves (so that OKHttp does not try to handle it transparently).


FYI: content uploaded by previous versions on the staging server was affected by an update issue which led to inconsistent headers and has been deleted.

**Closed as completed** 2024-02-19 12:06 UTC
Labels: fixed-pending-check
