### ISSUE TITLE
Scheduled job crashes: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#50] opened 2017-09-05 07:56 UTC
An app has stopped message is displayed by Android with the following in the logs:

```
09-05 11:46:58.306 25593-25593/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.toughra.ustadmobile, PID: 25593
                                                   java.lang.RuntimeException: Unable to create application com.ustadmobile.port.android.App: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                       at android.os.Parcel.readException(Parcel.java:1692)
                                                       at android.os.Parcel.readException(Parcel.java:1637)
                                                       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
                                                       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
                                                       at com.evernote.android.job.v21.JobProxy21.schedule(JobProxy21.java:198)
                                                       at com.evernote.android.job.v21.JobProxy21.plantPeriodic(JobProxy21.java:92)
                                                       at com.evernote.android.job.JobManager.scheduleWithApi(JobManager.java:282)
                                                       at com.evernote.android.job.JobManager.schedule(JobManager.java:240)
                                                       at com.evernote.android.job.JobRequest.schedule(JobRequest.java:366)
                                                       at com.ustadmobile.port.android.App.scheduleJob(App.java:53)
                                                       at com.ustadmobile.port.android.App.onCreate(App.java:33)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
09-05 11:49:42.312 25982-25982/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.toughra.ustadmobile, PID: 25982
                                                   java.lang.RuntimeException: Unable to create application com.ustadmobile.port.android.App: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                       at android.os.Parcel.readException(Parcel.java:1692)
                                                       at android.os.Parcel.readException(Parcel.java:1637)
                                                       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
                                                       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
                                                       at com.evernote.android.job.v21.JobProxy21.schedule(JobProxy21.java:198)
                                                       at com.evernote.android.job.v21.JobProxy21.plantPeriodic(JobProxy21.java:92)
                                                       at com.evernote.android.job.JobManager.scheduleWithApi(JobManager.java:282)
                                                       at com.evernote.android.job.JobManager.schedule(JobManager.java:240)
                                                       at com.evernote.android.job.JobRequest.schedule(JobRequest.java:366)
                                                       at com.ustadmobile.port.android.App.scheduleJob(App.java:53)
                                                       at com.ustadmobile.port.android.App.onCreate(App.java:33)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
09-05 11:49:50.461 26040-26040/com.toughra.ustadmobile E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.toughra.ustadmobile, PID: 26040
                                                                         java.lang.RuntimeException: Unable to create application com.ustadmobile.port.android.App: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
                                                                             at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                          Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                                             at android.os.Parcel.readException(Parcel.java:1692)
                                                                             at android.os.Parcel.readException(Parcel.java:1637)
                                                                             at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
                                                                             at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
                                                                             at com.evernote.android.job.v21.JobProxy21.schedule(JobProxy21.java:198)
                                                                             at com.evernote.android.job.v21.JobProxy21.plantPeriodic(JobProxy21.java:92)
                                                                             at com.evernote.android.job.JobManager.scheduleWithApi(JobManager.java:282)
                                                                             at com.evernote.android.job.JobManager.schedule(JobManager.java:240)
                                                                             at com.evernote.android.job.JobRequest.schedule(JobRequest.java:366)
                                                                             at com.ustadmobile.port.android.App.scheduleJob(App.java:53)
                                                                             at com.ustadmobile.port.android.App.onCreate(App.java:33)
                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                                             at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

```

**Comment by varunasingh** [comment] 2017-09-07 13:22
Full stacktrace: 

09-07 17:21:22.447 28448-28448/? I/art: Late-enabling -Xcheck:jni
09-07 17:21:22.687 28448-28448/com.toughra.ustadmobile.uswdp W/System: ClassLoader referenced unknown path: /data/app/com.toughra.ustadmobile.uswdp-2/lib/arm64
09-07 17:21:22.691 28448-28448/com.toughra.ustadmobile.uswdp E/asset: AssetManager::addSystemOverlays delete oidmap
09-07 17:21:22.710 28448-28448/com.toughra.ustadmobile.uswdp I/InstantRun: starting instant run server: is main process
09-07 17:21:22.713 28448-28448/com.toughra.ustadmobile.uswdp I/System.out: UMSyncJob:App:
09-07 17:21:22.734 28448-28448/com.toughra.ustadmobile.uswdp I/System.out: UMSyncJob:App: Currently there are :0 jobs running.
09-07 17:21:22.734 28448-28448/com.toughra.ustadmobile.uswdp I/System.out: UMSyncJob:App: Currently there are :0 UMSyncJobs running.
09-07 17:21:22.739 28448-28448/com.toughra.ustadmobile.uswdp I/System.out: UMSyncJob:App: Job : 0 not running. Scheduling it..
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.evernote.android.job.gcm.PlatformGcmService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GcmTaskService;
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at boolean com.evernote.android.job.util.GcmAvailableHelper.isGcmApiSupported(android.content.Context) (GcmAvailableHelper.java:-1)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at boolean com.evernote.android.job.util.JobApi.isSupported(android.content.Context) (JobApi.java:146)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.evernote.android.job.JobProxy$Common.cleanUpOrphanedJob(android.content.Context, int) (JobProxy.java:280)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.evernote.android.job.JobManager.schedule(com.evernote.android.job.JobRequest) (JobManager.java:224)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at int com.evernote.android.job.JobRequest.schedule() (JobRequest.java:366)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.ustadmobile.port.android.App.scheduleJob() (App.java:63)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.ustadmobile.port.android.App.onCreate() (App.java:41)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1025)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5582)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1596)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.os.Looper.loop() (Looper.java:154)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6317)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:872)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:762)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GcmTaskService" on path: DexPathList[[zip file "/data/app/com.toughra.ustadmobile.uswdp-2/base.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.toughra.ustadmobile.uswdp-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.to
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at boolean com.evernote.android.job.util.GcmAvailableHelper.isGcmApiSupported(android.content.Context) (GcmAvailableHelper.java:-1)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at boolean com.evernote.android.job.util.JobApi.isSupported(android.content.Context) (JobApi.java:146)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.evernote.android.job.JobProxy$Common.cleanUpOrphanedJob(android.content.Context, int) (JobProxy.java:280)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.evernote.android.job.JobManager.schedule(com.evernote.android.job.JobRequest) (JobManager.java:224)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at int com.evernote.android.job.JobRequest.schedule() (JobRequest.java:366)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.ustadmobile.port.android.App.scheduleJob() (App.java:63)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.ustadmobile.port.android.App.onCreate() (App.java:41)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1025)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5582)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1596)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.os.Looper.loop() (Looper.java:154)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6317)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:872)
09-07 17:21:22.757 28448-28448/com.toughra.ustadmobile.uswdp I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:762)
09-07 17:21:22.768 28448-28448/com.toughra.ustadmobile.uswdp D/AndroidRuntime: Shutting down VM
09-07 17:21:22.768 28448-28448/com.toughra.ustadmobile.uswdp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.toughra.ustadmobile.uswdp, PID: 28448
                                                                               java.lang.RuntimeException: Unable to create application com.ustadmobile.port.android.App: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5585)
                                                                                   at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6317)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                                Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
                                                                                   at android.os.Parcel.readException(Parcel.java:1691)
                                                                                   at android.os.Parcel.readException(Parcel.java:1636)
                                                                                   at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
                                                                                   at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
                                                                                   at com.evernote.android.job.v21.JobProxy21.schedule(JobProxy21.java:198)
                                                                                   at com.evernote.android.job.v21.JobProxy21.plantPeriodic(JobProxy21.java:92)
                                                                                   at com.evernote.android.job.JobManager.scheduleWithApi(JobManager.java:282)
                                                                                   at com.evernote.android.job.JobManager.schedule(JobManager.java:240)
                                                                                   at com.evernote.android.job.JobRequest.schedule(JobRequest.java:366)
                                                                                   at com.ustadmobile.port.android.App.scheduleJob(App.java:63)
                                                                                   at com.ustadmobile.port.android.App.onCreate(App.java:41)
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5582)
                                                                                   at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6317) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by varunasingh** [comment] 2017-09-20 16:51
Haven't seen this behavior since fix commit. Closing.

**Closed by varunasingh** 2017-09-20 16:51 UTC
