### ISSUE TITLE
Usability || Issues on Course Attendance Tab

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#573] opened 2023-08-18 11:26 UTC
**Describe the bug**

This bug report highlights several issues identified within the "Course Attendance" tab. These issues pertain to form field visibility, labeling inconsistencies, and unclear functionality, impacting the user experience and functionality of the attendance-related screens.

1. Form fields on the "Add a New Occurrence" screen are partially obscured by the header.
2. Both checkboxes on the "Record Attendance" screen are labeled "Mark All Absent."
3. The tick, x, and watch icon buttons on the "Record Attendance" screen lack clear explanations of their intended functions.

**To Reproduce**

1. Log in to the application.
2. Navigate to the courses page and click on the course already created
3. Access the "Attendance" tab.
4. Click on the "Record attendance" button, Navigate to the "Add a New Occurrence" screen, and observe the form field visibility issue.
5. Navigate to the "Record Attendance" screen and observe the labeling inconsistencies and unclear icon functionality.

**Expected behavior**

1. Form fields on the "Add a New Occurrence" screen should be fully visible and accessible, without being obscured by the header.
2. Checkbox labels on the "Record Attendance" screen should be distinct, accurately representing their corresponding actions - Mark all absent/mark all present
3. Icon buttons on the "Record Attendance" screen should have clear explanations of their intended functions.

**Screenshots**
![Screenshot from 2023-08-18 15-18-56](https://github.com/UstadMobile/UstadMobile/assets/78338755/bb568806-9779-4908-8f5c-4342ddd20bd9)
![Screenshot from 2023-08-18 15-18-40](https://github.com/UstadMobile/UstadMobile/assets/78338755/2df11e71-db3c-4bab-af7c-bab0d9d783b3)

**Comment by mikedawson** [comment] 2023-08-20 13:22
Re item #3 - the tick and cross next to the name have always been understood clearly by teacher as the buttons to make a student present or absent. We don't intend to change them. The 'watch' indicates that a student was late (or left early).

**Comment by gravitz** [comment] 2023-08-22 06:53
> Re item #3 - the tick and cross next to the name have always been understood clearly by teacher as the buttons to make a student present or absent. We don't intend to change them. The 'watch' indicates that a student was late (or left early).

Have these icons as they are also passed accessibility tests? While I can see how the functions of the tick and cross may be guessed correctly by users, I am not sure I can say the same for the watch. I suggest tooltips

**Comment by mikedawson** [comment] 2023-09-28 14:33
TODO:
1) Remove duplicate of "mark all absent" - should have mark all present and mark all absent.
2) Add tooltips to buttons for present/absent/partial attendance (React only)

**Comment by mikedawson** [comment] 2023-12-05 09:23
![WhatsApp Image 2023-12-05 at 13 22 28](https://github.com/UstadMobile/UstadMobile/assets/4280622/05ef7c59-56ac-4559-aa56-514368d651fb)

Done - mark all absent / present is corrected. Tooltips added.

**Closed as completed by mikedawson** 2023-12-05 09:23 UTC
Labels: bug, usability
