### ISSUE TITLE
Download panel buttons are not showing correctly

### ISSUE THREAD

**Issue by aakabir** [UstadMobile/UstadMobile#103] opened 2020-03-11 05:40 UTC
![VSOSchool 1 (5)](https://user-images.githubusercontent.com/33418194/76385864-0e51c580-638d-11ea-8905-8f17b843bd92.jpeg)

**Comment by mikedawson** [comment] 2020-03-12 08:56
This is reproduced and appears to be caused by the material design upgrade. Should be fixed in the next few days.

**Comment by mikedawson** [comment] 2020-10-20 07:10
This is obsolete

**Closed by mikedawson** 2020-10-20 07:10 UTC
