### ISSUE TITLE
Pdf Issue noted on Windows- Desktop || PDF screen getting zoomed out

### ISSUE THREAD

**Issue by poojaustad** [UstadMobile/UstadMobile#828] opened 2024-02-07 11:26 UTC
**Describe the bug**
When user add a pdf content and open PDF screen getting zoomed out

**To Reproduce**
1. Go to Library and add pdf content
2. Click on 'open button
3. Pdf gets open but screens get zoomed out and not visible to user

**Expected behavior**
When user add a pdf content and open PDF screen should be visible to the users

**Screenshots**
![MicrosoftTeams-image (3)](https://github.com/UstadMobile/UstadMobile/assets/78338755/92f71adb-93e2-4f16-b285-a55e08e01786)

Noted on Windows - desktop version

**Comment by mikedawson** [comment] 2024-02-09 07:59
Fixed in version 0.4.63 . This was caused by use of the image size measurements in compose that seemed to vary on Windows. This has been replaced with reading the size of each page of the PDF on load, and then creating correctly sized blank placeholder images (to avoid page jumping etc). 

![WhatsApp Image 2024-02-09 at 01 14 53](https://github.com/UstadMobile/UstadMobile/assets/4280622/e7318d45-c19b-4103-9955-6dce23c24eaf)

**Closed as completed** 2024-02-29 06:29 UTC
Labels: bug, fixed-pending-check
